# Generated by Django 5.0.4 on 2024-05-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("std_id", models.IntegerField()),
                ("std_name", models.CharField(max_length=40)),
                ("std_email", models.EmailField(max_length=40)),
                ("std_pass", models.CharField(max_length=10)),
            ],
        ),
    ]
