# Generated by Django 5.0.4 on 2024-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="comment",
            field=models.CharField(default="Not available", max_length=70),
        ),
    ]
